### ISSUE TITLE
1.20 Progress 

### ISSUE THREAD

**Issue by VoidLifter** [pascallj/mineshot-revived-fabric#17]
are there plans on making a version for 1.20?

if not is there another source that does?

**Comment by VoidLifter** [comment]
found it

**Comment by pascallj** [comment]
My own interest in Minecraft has fallen and if there is no big demand for this mod, then there is no incentive for me to keep it alive. Could you share which one you found with the community if anyone else is looking for this?

**Comment by VoidLifter** [comment]
sorry to here that, i hope you found something else that peaked your intrest, whatever it might be.

I tested the mod first to make shure that it works as intended, here is the link to the mod:
[Link to mod](https://www.curseforge.com/minecraft/mc-mods/fabrishot)

**Comment by pascallj** [comment]
Thank you! I have plenty (probably too much) other projects I want to work on, so no need to be sorry. And usually with my projects I have a personal need for them and therefore a decent amount of motivation to work on them.

If someone else has a working mod for this as well, I'll probably soon retire this project.
