### ISSUE TITLE
Please update the mod to 1.18.x

### ISSUE THREAD

**Issue by DearFox** [pascallj/mineshot-revived-fabric#3]
I really like this mod and the ability to take beautiful screenshots.
I would like to use it on 1.18.1 and later.
Are there any plans to update the mod to new current versions?

**Comment by pascallj** [comment]
I wasn't aware a new Minecraft has been released already. Not using it on a day-to-day basis. I've added it to my todo list :+1:

**Comment by Wiardo** [comment]
Yes, I agree with Dear Fox, I would also very much like to update this cool mod to 1.18.x

**Comment by pascallj** [comment]
Your wish is my command. I've just published version [3.0.0-beta.1](https://github.com/pascallj/mineshot-revived-fabric/releases/tag/v3.0.0-beta.1) :tada:. No major changes were necessary. Feel free to test it.
